# Generated by Django 3.2.8 on 2021-10-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211008_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='binding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
